### PR TITLE
Clarify fork purposes (LGPL)

### PR DESCRIPTION
**Pull request by shirt-dev**
Making forks with different licenses isn't nice.

### CODE REVIEW

**Comment by ptrcnull** [comment]
That seems extremely petty for a developer of another youtube-dl fork.

**Comment by shirt-dev** [comment]
> That seems extremely petty for a developer of another youtube-dl fork.

I guess it is pretty petty, could have worded the title better, main issue here is that LGPL means that upstream/other forks can't use the code without switching to LGPL in this case.

**Comment by alufers** [comment]
Maybe someone has invested some time into theirs project, and doesn't want somebody to take it and incorporate into closed source projects, or change the license?

**Comment by selfisekai** [comment]
This is an LGPL fork for a reason - improvements to it must be published for the community.

And [upstream didn't ever care](https://github.com/pulls?q=is%3Apr+author%3Aselfisekai+user%3Aytdl-org) when I was submitting code on Unlicense, which is actually one of the reasons why this fork exists in first place.

**Comment by shirt-dev** [comment]
Sorry

**Pull request closed without merging**
